workflows:
  ios-local-dev:
    name: iOS – Dev IPA using uploaded certs/profile
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter deps
        script: flutter pub get

      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign

      - name: Import signing assets
        script: |
          set -e
          keychain initialize
          keychain add-certificates         # imports your WClub Dev P12
          xcode-project use-profiles        # applies WClub Dev Profile (com.example.wClub)
          security find-identity -v -p codesigning || true
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Sign & export IPA (development)
        script: |
          set -e
          if [ -d "ios/Runner.xcworkspace" ]; then
            xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner --export-method development
          else
            xcode-project build-ipa --project ios/Runner.xcodeproj      --scheme Runner --export-method development
          fi

    artifacts:
      - build/ios/ipa/*.ipa
