workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      vars:
        # IMPORTANT: Make sure this matches your actual bundle ID from Xcode
        BUNDLE_ID: "com.example.w_club" 
    scripts:
      - flutter pub get
      - flutter build ipa --export-options-plist=ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: 2NN3S2N4RT
        issuer_id: 6babf10e-105d-4843-975f-92365a4a8c06
