workflows:
  ios-local-dev:
    name: iOS – Dev IPA (diagnostic)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Import signing assets (don’t fail on missing)
        script: |
          # Don't die on non-zero so we can see output
          set +e
          keychain initialize
          echo "=== keychain add-certificates ==="
          keychain add-certificates
          echo "exit code: $?"

          echo "=== xcode-project use-profiles ==="
          xcode-project use-profiles
          echo "exit code: $?"

          echo "=== Provisioning profiles directory ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

          echo "=== Code signing identities in keychain ==="
          security find-identity -v -p codesigning || true

      - name: Install CocoaPods workspace
        script: |
          set -e
          cd ios
          pod repo update || true
          pod install
          cd ..

      - name: Flutter deps
        script: flutter pub get

      - name: Build signed IPA
        script: flutter build ipa --export-method development

    artifacts:
      - build/ios/ipa/*.ipa
