workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      groups: # <-- THIS IS THE CRITICAL FIX
        - app_store_connect 
      vars:
        BUNDLE_ID: "com.example.wClub" 
    scripts:
      - keychain initialize
      - app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
      - keychain add-certificates
      - xcode-project use-profiles
      - flutter pub get
      - flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
