workflows:
  ios-device-build:
    name: iOS – Development IPA for iPads
    environment:
      flutter: stable
      xcode: latest
      vars:
        # Must match the bundle id in ios/Runner.xcodeproj (yours already does)
        BUNDLE_ID: "com.example.wClub"
    # <-- No groups or ASC env vars needed when using ios_signing automatic mode
    scripts:
      - flutter pub get
      - flutter build ipa --export-method development
    ios_signing:
      # This block turns on Automatic iOS code signing
      distribution_type: development
      bundle_identifier: $BUNDLE_ID
    artifacts:
      - build/ios/ipa/*.ipa
