workflows:
  ios-local-dev:
    name: iOS – Dev IPA (direct files)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Decode & import signing files
        script: |
          set -e
          keychain initialize

          P12_PATH="$CM_BUILD_DIR/ios_dev.p12"
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_PATH="$PROFILE_DIR/wclub.mobileprovision"
          mkdir -p "$PROFILE_DIR"

          # decode to real files
          printf "%s" "$CERTIFICATE_P12_B64" | base64 --decode > "$P12_PATH"
          printf "%s" "$DEV_PROFILE_B64"     | base64 --decode > "$PROFILE_PATH"

          # import p12 and confirm identities
          security import "$P12_PATH" -P "$CERTIFICATE_PASSWORD" -A
          security find-identity -v -p codesigning

      - name: Install CocoaPods workspace
        script: |
          cd ios
          pod repo update || true
          pod install
          cd ..

      - name: Flutter deps
        script: flutter pub get

      - name: Build signed IPA (Development)
        script: flutter build ipa --export-method development

    artifacts:
      - build/ios/ipa/*.ipa
