workflows:
  ios-local-dev:
    name: iOS – Dev IPA using uploaded certs/profile
    environment:
      flutter: stable
      xcode: latest

    scripts:
      # 1) Get deps (lets Flutter generate any iOS files it needs)
      - name: Flutter deps
        script: flutter pub get

      # 2) Build the iOS app WITHOUT signing (produces the Xcode workspace & archive inputs)
      - name: Build iOS (no codesign)
        script: flutter build ios --release --no-codesign

      # 3) Import your uploaded p12 and apply your uploaded provisioning profile
      - name: Import signing assets
        script: |
          set -e
          keychain initialize
          keychain add-certificates || true          # imports WClub Dev P12
          xcode-project use-profiles || true         # applies WClub Dev Profile (com.example.wClub)
          echo "=== Identities ==="
          security find-identity -v -p codesigning || true
          echo "=== Profiles ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      # 4) Export the signed IPA from the Xcode archive using the installed profile/cert
      - name: Sign & export IPA (development)
        script: |
          set -e
          # Build and sign using Codemagic's xcode-project helper
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-path build/ios/archive/Runner.xcarchive \
            --export-method development

    artifacts:
      - build/ios/ipa/*.ipa
