workflows:
  ios-device-build:
    name: iOS – Development IPA for iPads
    environment:
      flutter: stable
      xcode: latest
      # This group must contain the 3 vars listed below.
      groups:
        - "My App Store Key"
      vars:
        # Must match Runner.xcodeproj (yours already does).
        BUNDLE_ID: "com.example.wClub"
    scripts:
      - keychain initialize

      # Fetch dev certs & provisioning profiles via ASC API
      - |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_DEVELOPMENT \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --create

      - keychain add-certificates
      - xcode-project use-profiles
      - flutter pub get

      # Build a Development-signed IPA (for local install)
      - flutter build ipa --export-method development

    artifacts:
      - build/ios/ipa/*.ipa

    # No App Store publishing – we’re just saving the IPA
